language: java

jdk:
  - oraclejdk8
  - openjdk8

script: MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=info mvn test javadoc:javadoc

after_success:
  -  MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=info mvn clean cobertura:cobertura -Dcobertura.report.format=xml coveralls:cobertura
